version: 2
jobs:
  build:
    docker:
      # Circle CI does not currently have a node 8 Image
      # https://circleci.com/docs/2.0/circleci-images/#nodejs
      - image: circleci/node:7.10.0
    steps:
      - checkout
      # Download cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install 
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:7.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run test:ci
  lint:
    docker:
      - image: circleci/node:7.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm run lint
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
